name: flutter_weather
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  http: ^1.1.0
  shared_preferences: ^2.0.13
  geolocator: ^9.0.0
  geocoding: ^2.0.4
  intl: ^0.18.1
  google_maps_flutter: ^2.5.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.1.6
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  country_picker: ^2.0.23
  fl_chart: ^0.65.0
  table_calendar: ^3.0.8
  share_plus: ^7.2.1
  cached_network_image: ^3.3.0
  material_floating_search_bar_2: ^0.5.0
  phosphor_flutter: ^2.0.0
  flutter_animate: ^4.2.0
  flutter_local_notifications: ^15.1.1
  url_launcher: ^6.1.14
  flutter_markdown: ^0.6.17
  in_app_purchase: ^3.1.7
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  supercharged: ^2.1.1
  rive: ^0.11.16
  animated_text_kit: ^4.2.2
  google_fonts: ^4.0.0
  latlong2: ^0.9.0
  flutter_map: ^6.1.0
  simple_animations: ^5.2.0
  image_picker: ^0.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/animations/
    - assets/images/
    - assets/weather_conditions/
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
